"""Initial migration.

Revision ID: 007c0ab09049
Revises: 
Create Date: 2024-07-22 11:03:03.928760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007c0ab09049'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field1', sa.String(length=64), nullable=True),
    sa.Column('field2', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_data')
    # ### end Alembic commands ###
